In [2]:
# Import libabries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from wordcloud import WordCloud

In [3]:
!pip install wordcloud

Requirement already satisfied: wordcloud in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (1.9.6)
Requirement already satisfied: numpy>=1.19.3 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from wordcloud) (2.1.3)
Requirement already satisfied: pillow in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from wordcloud) (11.0.0)
Requirement already satisfied: matplotlib in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from wordcloud) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->wordcloud) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->wordcloud) (4.55.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->wordcloud) (1.4.7)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->wordcloud) (25.0)
Requirement already satisfied: pyparsing>=3 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->wordcloud) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lenovo\appdata\roaming\python\python311\site-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.16.0)

[notice] A new release of pip is available: 23.1.2 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
# Read the file 
df = pd.read_csv('netflix.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,25-Sep-21,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,24-Sep-21,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,24-Sep-21,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,24-Sep-21,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,24-Sep-21,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
# Explore file
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [6]:
# Count null rows 
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [7]:
# Null processing
# Fill Unknown for director, country and cast columns
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')

# Fill the most appeared values for rating column
df['rating'] = df['rating'].fillna(df['rating'].mode()[0])

# Delete null rows for date_added and release_year
df.dropna(subset=['date_added', 'duration'], inplace=True)

# Check null
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [11]:
# Split the genre collumn
genre_df = df[['country','show_id', 'listed_in']].dropna()

# Split string by ','
genre_df['listed_in'] = genre_df['listed_in'].str.split(',')
df_exploded = genre_df.explode('listed_in')
df_exploded['listed_in'] = df_exploded['listed_in'].str.strip()

In [12]:
df_exploded.head()

         country show_id               listed_in
0  United States      s1           Documentaries
1   South Africa      s2  International TV Shows
1   South Africa      s2               TV Dramas
1   South Africa      s2            TV Mysteries
2        Unknown      s3          Crime TV Shows

In [13]:
# Save file
df_exploded.to_csv('netflix_genres.csv')